name: repetitor
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.3

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqflite: ^2.4.2
  path: ^1.9.1
  intl: ^0.20.2
  path_provider: ^2.1.5
  file_picker: ^10.3.7
  permission_handler: ^12.0.1

  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/pen-icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
